workflow build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,9 +27,13 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install pyinstaller
-        pwd
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-
+    
+    - name: current directories
+      run: |
+          pwd
+          ls
+          ls dist
     - name: Build binary
       run: pyinstaller gdrive.py
 
@@ -42,10 +46,12 @@ jobs:
 
     - name: Verify zip file exists
       run: |
-        if [ ! -f "dist/gdrive-${{ env.RELEASE_VERSION }}.zip" ]; then
-          echo "Error: gdrive-${{ env.RELEASE_VERSION }}.zip not found in dist/"
-          exit 1
-        fi
+          if [ -f "dist/gdrive-v1.0.2.zip" ]; then
+            echo "gdrive-v1.0.2.zip found in dist/"
+          else
+            echo "Error: gdrive-v1.0.2.zip not found in dist/"
+            exit 1
+          fi
 
     - name: Create Release
       id: create_release
@@ -64,6 +70,6 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: dist/
+        asset_path: dist/gdrive-${{ env.RELEASE_VERSION }}.zip
         asset_name: gdrive-${{ env.RELEASE_VERSION }}.zip
         asset_content_type: application/zip
